CMakeList: move include-path for clients earlier in stage
In 2606d2965471 (I3DS-140: split out clients into own library), client
and emulators were split out to generate separate .so files. In this
commit, client headers were mistakenly put under emulators/include.

3755bd832014 (Moves client headers to client dir) corrects this, but a
latent bug in the build setup from 2606d2965471 caused the include-path
to include client-files too late yielding

     fatal error: i3ds/trigger_client.hpp: No such file or directory

Move include_directory of clients/include to *before* we add the
subdirectories so that emulators also see these headers.

Cc: Fredrik Bakkevig Haugli <fredrik.haugli@sintef.no>